# Generated by Django 5.2.6 on 2025-09-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề trang')),
                ('slug', models.SlugField(help_text="Đường dẫn tĩnh, ví dụ: 'about-us', 'contact'", max_length=100, unique=True)),
                ('content', models.TextField(verbose_name='Nội dung trang')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hiển thị trang?')),
            ],
            options={
                'verbose_name': 'Trang tĩnh',
                'verbose_name_plural': 'Các trang tĩnh',
            },
        ),
    ]
