# Generated by Django 5.2.6 on 2025-09-27 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Các danh mục',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('excerpt', models.TextField(blank=True, verbose_name='Đoạn trích ngắn')),
                ('cover_image', models.ImageField(upload_to='blog_covers/', verbose_name='Ảnh bìa')),
                ('status', models.CharField(choices=[('DF', 'Bản nháp'), ('PB', 'Đã xuất bản')], default='DF', max_length=2, verbose_name='Trạng thái')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Các bài viết',
                'ordering': ['-created_at'],
            },
        ),
    ]
